export const VALID_EXTRA_CATEGORIES = [
  'politica',
  'política',
  'governo',
  'stf',
  'judiciário',
  'história',
  'relações internacionais',
  'terrorismo',
  'geografia',
  'economia',
  'internacional',
  'gestão pública',
  'justiça',
  'justica',
  'outro',
  'outros',
];

export const VALID_KEY_WORDS = [
  'lula',
  'bolsonaro',
  'musk',
  'dilma',
  'stf',
  'STF',
  'moraes',
  'michelle',
  'ministro',
  'ministros',
  'terrorismo',
  'terroristas',
  'hamas',
  'constituição',
  'inconstitucionalidade',
  'câmara',
  'presidente',
  'autoritarismo',
  'judiciário',
  'judiciario',
  'CNJ',
  'eleicoes',
  'eleições',
  'politica',
  'política',
  'TSE',
  'narrativas',
];
